version: "3"

services:
  refine:
    image: ontotext/refine
    restart: unless-stopped
    environment:
      SERVER_HOST: 10.95.1.12
    ports:
      - "7333:7333"
    volumes:
      - refine_data:/opt/ontorefine/data

volumes:
  refine_data: